letim_calender_gettunels:
    path:     /calender/gettunels
    defaults: { _controller: LetimCalenderBundle:Default:getTunels }
#    methods:  [GET]
    
letim_calender_test:
    path:     /calender/test
    defaults: { _controller: LetimCalenderBundle:Default:getSome }
letim_calender_page:
    path:     /calendar/page
    defaults: { _controller: LetimCalenderBundle:Default:calendar }
letim_bron_get_plan:
    path: /bronirovanie/plan
    defaults: { _controller: LetimCalenderBundle:Default:bronform }
letim_bron_set_plan:
    path: /bronirovanie/save
    defaults: { _controller: LetimCalenderBundle:Default:newBron }
letim_bron_page:
    path:     /bronirovanie/{date}
    defaults: { _controller: LetimCalenderBundle:Default:bronirovanie ,date:''}
sonata_admin_custompage:
    pattern:  /admin/bronirovanie
    defaults: { _controller: LetimCalenderBundle:Admin:bronirovanie }
letim_test_pages:
    path:     /testpage
    defaults: { _controller: LetimCalenderBundle:Test:test }


#    methods:  [POST]