letim_calender_gettunels:
    path:     /calender/gettunels
    defaults: { _controller: LetimCalenderBundle:Default:getTunels }
#    methods:  [GET]
    
letim_calender_test:
    path:     /calender/test
    defaults: { _controller: LetimCalenderBundle:Default:getSome }
letim_calender_page:
    path:     /calendar/page
    defaults: { _controller: LetimCalenderBundle:Default:calendar }
letim_bron_page:
    path:     /bronirovanie
    defaults: { _controller: LetimCalenderBundle:Default:bronirovanie }
letim_bron_get_plan:
    path: /bronirovanie/plan
    defaults: { _controller: LetimCalenderBundle:Default:bronform }
#    methods:  [POST]