Letim\MenuBundle\Entity\MenuItem:
    type: entity
    table: menu_item
    indexes:
        menu_key:
            columns:
                - menu_id
        page_key:
            columns:
                - page_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        menu:
            targetEntity: Menu
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                menu_id:
                    referencedColumnName: id
            orphanRemoval: false
        page:
            targetEntity: Page
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                page_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
