Letim\FaqBundle\Entity\PageFaq:
    type: entity
    table: page_faq
    indexes:
        page:
            columns:
                - page
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        page:
            targetEntity: Page
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                page:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
