parameters:
#    letim_review.example.class: Letim\ReviewBundle\Example

services:
#    letim_review.example:
#        class: %letim_review.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     admin.review:
         class: Letim\ReviewBundle\Admin\ReviewAdmin
         tags:
         - { name:  sonata.admin, manager_type: orm, group: Отзывы, label: Добавить отзыв}
         arguments: [null, Letim\ReviewBundle\Entity\Review, SonataAdminBundle:CRUD]