Letim\ReviewBundle\Entity\Review:
    properties:
        author:
            - NotBlank: ~
        text:
            - NotBlank: ~
        email:
            - Email:
                message: Email не является валидным "{{ value }}".
                checkMX: false