Letim\PageBundle\Entity\Page:
    type: entity
    table: page
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        url:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        text:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        active:
            type: boolean
            nullable: true
            comment: ''
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: updated_at
        homePage:
            type: boolean
            nullable: true
            comment: ''
            column: home_page
    lifecycleCallbacks: {  }
