Letim\PhotoBundle\Entity\Photo:
    type: entity
    table: photo
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        date:
            type: datetime
            nullable: false
            comment: ''
        photo:
            type: array
            nullable: true
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
